language: java
sudo: required
services:
- docker
jdk:
- oraclejdk11
install: true
env:
- GROUP=weaveworksdemos COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=shipping;
script:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- set -e
- "./scripts/build.sh;"
- "./test/test.sh unit.py"
- "./test/test.sh component.py"
after_success:
- docker buildx create --name shippingbk
- docker buildx use shippingbk
- docker buildx inspect --bootstrap
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASS}
- docker buildx build -t ajv21/shipping:latest --platform linux/amd64 --push .
- docker buildx rm shippingbk
notifications:
  slack:
    secure: tns9qBsF5fcLCeBbMyYEtecnMEDGWVhjK3hD/O022v+4DgDn8r0ne29mK06jrUaJ7L6xSlwy79QAvTklY/sr0WjRRB0ka7btmNVwwYinn6VJYVkSA2Drl5Wbti/Jap9PtH2/GIgObqTlYPfeoDdkIxKS04PjSJTwG22g/AZsAzrIiZHT6rI19JIBrskmfQkPEQuBbfFlP/YDkBZQ2x7hMXuHrxrUbsVNAQ7kFlns7wzTzPpoy2tf8NcYZsh9I7j7YjTW5zwDQe86Yc+AaGuT84xGwt4CShycDQQ0Tck/vb+yT2+k3pB9Bx/p19iB7QJR3TxfLeDJ7F6Oh/PsD6irh3vSeWdqaK4dtSszzHY94ec7vFWE8k9tceJMqWMflPHPiJLV2MJ6kxrCbI6U4c0+HYQm0cGAp+QH9KRjVvosT1U2TiPDBTW028O7VV/BcuU+3FZzmZfF2JDCNPotTwsK0IVgEeaTlqkMYBy5zWN904wudctGCmJBlNMlAJaT7v0F4sE/3UKqVegbfhvFsCUlXMbATqAOaF5vM5DDT0b670jRcIyi9LL6X2z8oegV2xNbCLB2V52IdozTwA36sof4uHMZsy2yejm2c7/DTz0jlhoUjsSCr4/ZOAK36pJk94jeQyUc858ygq0eK+TsR/xFdsZZTSLu0s0qwWbQn6jUvzk=
